set termencoding=utf-8
set nocompatible
syntax on
set showmode
set showcmd
set mouse=a
set t_Co=256
filetype indent on
set autoindent
set tabstop=2
set shiftwidth=4
set expandtab
set softtabstop=2
set number
set cursorline
set nowrap
set linebreak
set wrapmargin=2
set scrolloff=7
set sidescrolloff=15
set laststatus=2
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set undofile
set autoread
